name: Run notion to generate md file

on:
  schedule:
    - cron:  '1/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 12.19.1

      - name: Install yarn
        run: npm install -g yarn

      - name: Use cache for yarn if available
        uses: c-hive/gha-yarn-cache@v1

      - name: Install yarn dependencies
        run: yarn install

      - name: Run notion fetcher
        run: node notion-fetcher.js

      - name: Commit to repo
        uses: EndBug/add-and-commit@v7
        with:
          add: 'content'
          message: 'Sync pages with notion'